<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<CodeAnalysisRuleSet>../settings.ruleset</CodeAnalysisRuleSet>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Validators\Sourse\**" />
    <EmbeddedResource Remove="Validators\Sourse\**" />
    <None Remove="Validators\Sourse\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="8.0.0" />
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentResults" Version="3.15.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="11.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="2.5.1" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="8.14.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Streetcode.DAL\Streetcode.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\Analytics\" />
    <Folder Include="MediatR\AdditionalContent\Tag\" />
    <Folder Include="Exceptions\" />
    <Folder Include="DTO\Instagram\" />
    <Folder Include="Validators\Email\" />
    <Folder Include="Validators\Helpers\" />
    <Folder Include="Validators\Payment\" />
    <Folder Include="Validators\Partners\" />
    <Folder Include="Validators\Team\TeamMembersLinks\" />
    <Folder Include="Validators\Team\Position\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Errors.AdditionalContent.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.AdditionalContent.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.Common.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.Email.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.Email.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.RelatedTerm.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.RelatedTerm.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.Sources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.Sources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.Streetcode.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.Streetcode.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MediatR.Payment.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MediatR.Payment.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Errors.AdditionalContent.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.AdditionalContent.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.Common.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.Email.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Email.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.RelatedTerm.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.RelatedTerm.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.Sources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Sources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.Streetcode.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Streetcode.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MediatR.Payment.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MediatR.Payment.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
