//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors_Streetcode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors_Streetcode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.Errors.Streetcode", typeof(Errors_Streetcode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map streetcode to {0}.
        /// </summary>
        public static string CannotMap {
            get {
                return ResourceManager.GetString("CannotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetcode with id: {0} doesn`t exist.
        /// </summary>
        public static string DoesnotExist {
            get {
                return ResourceManager.GetString("DoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change status of streetcode to deleted.
        /// </summary>
        public static string FailedToChangeStatusToDeleted {
            get {
                return ResourceManager.GetString("FailedToChangeStatusToDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No streetcodes exist now.
        /// </summary>
        public static string NotExistNow {
            get {
                return ResourceManager.GetString("NotExistNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streetcode not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any streetcode with corresponding {0}: {1}.
        /// </summary>
        public static string NotFoundBy {
            get {
                return ResourceManager.GetString("NotFoundBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a relation between streetcodes with corresponding ids: {0} &amp; {1}.
        /// </summary>
        public static string NotFoundRelation {
            get {
                return ResourceManager.GetString("NotFoundRelation", resourceCulture);
            }
        }
    }
}
