//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors_AdditionalContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors_AdditionalContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.Errors.AdditionalContent", typeof(Errors_AdditionalContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to streetcodeCoordinate.
        /// </summary>
        internal static string Coordinate_CannotConvertNull {
            get {
                return ResourceManager.GetString("Coordinate_CannotConvertNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a streetcodeCoordinate.
        /// </summary>
        internal static string Coordinate_FailedToCreate {
            get {
                return ResourceManager.GetString("Coordinate_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a streetcodeCoordinate.
        /// </summary>
        internal static string Coordinate_FailedToDelete {
            get {
                return ResourceManager.GetString("Coordinate_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a streetcodeCoordinate.
        /// </summary>
        internal static string Coordinate_FailedToUpdate {
            get {
                return ResourceManager.GetString("Coordinate_FailedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinates by a streetcode id: {0}, because such streetcode doesn`t exist.
        /// </summary>
        internal static string Coordinate_NotFound_StreetcodeDoesNotExist {
            get {
                return ResourceManager.GetString("Coordinate_NotFound_StreetcodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinate with corresponding categoryId: {0}.
        /// </summary>
        internal static string Coordinate_NotFoundByCategory {
            get {
                return ResourceManager.GetString("Coordinate_NotFoundByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinates by a streetcode id: {0}.
        /// </summary>
        internal static string Coordinate_NotFoundByStreetcode {
            get {
                return ResourceManager.GetString("Coordinate_NotFoundByStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any subtitles.
        /// </summary>
        internal static string Subtitle_NotFoundAny {
            get {
                return ResourceManager.GetString("Subtitle_NotFoundAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a subtitle with corresponding id: {0}.
        /// </summary>
        internal static string Subtitle_NotFoundById {
            get {
                return ResourceManager.GetString("Subtitle_NotFoundById", resourceCulture);
            }
        }
    }
}
